### ISSUE TITLE
Meta: ensure all of the paths are complete and assemble the correct forms

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-CLAGuardianship#82]
See spreadsheet: https://lemmalegal.sharepoint.com/:x:/s/LemmaLegal/EZCDGLuySN5JjnROzy3KKj4BBFThzrprAPCM5i-H8w2KdA?e=brFTsG

- [x] Caregiver authorization / temporary agent
- [x] Appointing a guardian (petition)
- [x] Removing or replacing a guardian
- [x] Parent participation in the guardianship hearing: objection or waiver and consent
